import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useContext } from "react";
import { useCtx } from "../contexts/AuthContext";
import Router from "next/router";
import { Spinner } from "../components/Spinner";
import { useQuery } from "@apollo/client";
import { GET_ACCOUNT } from "../queries";
import ClientOnly from "../components/ClientOnly";
const Home: NextPage = () => {
	const authContext = useCtx();
	const account_id = authContext.user?.account_id;

	const {
		loading: accountLoading,
		error,
		data,
	} = useQuery(GET_ACCOUNT, {
		variables: {
			accountId: account_id,
		},
	});

	if (accountLoading) return <Spinner loading={authContext.loading} />;
	if (!authContext.isAuthenticated) Router.push("/signin");
	if (data) {
		console.log("returned account", data);
	}

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<div>
				{authContext.loading && <h1>Loading</h1>}

				<h1>Welcome {data?.account.account.email}</h1>
				<h1
					className='text-red-400'
					onClick={() => {
						authContext.logout("/signin");
					}}
				>
					Logout
				</h1>
				<Link href='/signin'>
					<a>Sign in</a>
				</Link>
				<Link href='/signup'>
					<a>Sign up</a>
				</Link>
				<Link href='/profile'>
					<a>Profile</a>
				</Link>
			</div>
		</div>
	);
};

export default Home;
